const mongoose = require('mongoose');

// Define schema for your vocabulary
const vocabularySchema = new mongoose.Schema({
  english: String,
  slovak: String,
  category: String,
});

// Define model for vocabulary
const Vocabulary = mongoose.model('Vocabulary', vocabularySchema);

// Connect to MongoDB
mongoose.connect("mongodb+srv://hernanvb:kWCfwONpotUZXV0s@slovaklingo.yisiz6k.mongodb.net/?retryWrites=true&w=majority&appName=SlovakLingo", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Sample vocabulary data
const categories = {
  basics: [
    { english: 'yes', slovak: 'áno', category: 'basics' },
    { english: 'no', slovak: 'nie', category: 'basics' },
    { english: 'please', slovak: 'prosím', category: 'basics' },
    { english: 'thank you', slovak: 'ďakujem', category: 'basics' },
    { english: 'you\'re welcome', slovak: 'prosím', category: 'basics' },
    { english: 'excuse me', slovak: 'prepáčte', category: 'basics' },
    { english: 'I\'m sorry', slovak: 'prepáč', category: 'basics' },
    { english: 'goodbye', slovak: 'dovidenia', category: 'basics' },
    { english: 'hello', slovak: 'ahoj', category: 'basics' },
    { english: 'bye', slovak: 'čau', category: 'basics' },
    { english: 'hi', slovak: 'ahoj', category: 'basics' },
  ],
  numbers: [
    { english: 'one', slovak: 'jeden', category: 'numbers' },
    { english: 'two', slovak: 'dva', category: 'numbers' },
    { english: 'three', slovak: 'tri', category: 'numbers' },
    { english: 'four', slovak: 'štyri', category: 'numbers' },
    { english: 'five', slovak: 'päť', category: 'numbers' },
    { english: 'six', slovak: 'šesť', category: 'numbers' },
    { english: 'seven', slovak: 'sedem', category: 'numbers' },
    { english: 'eight', slovak: 'osem', category: 'numbers' },
    { english: 'nine', slovak: 'deväť', category: 'numbers' },
    { english: 'ten', slovak: 'desať', category: 'numbers' },
  ],
  colors: [
    { english: 'red', slovak: 'červená', category: 'colors' },
    { english: 'orange', slovak: 'oranžová', category: 'colors' },
    { english: 'yellow', slovak: 'žltá', category: 'colors' },
    { english: 'green', slovak: 'zelená', category: 'colors' },
    { english: 'blue', slovak: 'modrá', category: 'colors' },
    { english: 'purple', slovak: 'fialová', category: 'colors' },
    { english: 'pink', slovak: 'ružová', category: 'colors' },
    { english: 'brown', slovak: 'hnedá', category: 'colors' },
    { english: 'black', slovak: 'čierna', category: 'colors' },
    { english: 'white', slovak: 'biela', category: 'colors' },
    { english: 'gray', slovak: 'šedá', category: 'colors' },
  ],
  daysMonths: [
    { english: 'Monday', slovak: 'pondelok', category: 'days and months' },
    { english: 'Tuesday', slovak: 'utorok', category: 'days and months' },
    { english: 'Wednesday', slovak: 'streda', category: 'days and months' },
    { english: 'Thursday', slovak: 'štvrtok', category: 'days and months' },
    { english: 'Friday', slovak: 'piatok', category: 'days and months' },
    { english: 'Saturday', slovak: 'sobota', category: 'days and months' },
    { english: 'Sunday', slovak: 'nedeľa', category: 'days and months' },
    { english: 'January', slovak: 'január', category: 'days and months' },
    { english: 'February', slovak: 'február', category: 'days and months' },
    { english: 'March', slovak: 'marec', category: 'days and months' },
    { english: 'April', slovak: 'apríl', category: 'days and months' },
    { english: 'May', slovak: 'máj', category: 'days and months' },
    { english: 'June', slovak: 'jún', category: 'days and months' },
    { english: 'July', slovak: 'júl', category: 'days and months' },
    { english: 'August', slovak: 'august', category: 'days and months' },
    { english: 'September', slovak: 'september', category: 'days and months' },
    { english: 'October', slovak: 'október', category: 'days and months' },
    { english: 'November', slovak: 'november', category: 'days and months' },
    { english: 'December', slovak: 'december', category: 'days and months' },
  ],
  seasons: [
    { english: 'spring', slovak: 'jar', category: 'seasons' },
    { english: 'summer', slovak: 'leto', category: 'seasons' },
    { english: 'autumn', slovak: 'jeseň', category: 'seasons' },
    { english: 'winter', slovak: 'zima', category: 'seasons' },
  ],
  directions: [
    { english: 'north', slovak: 'sever', category: 'directions' },
    { english: 'south', slovak: 'juh', category: 'directions' },
    { english: 'east', slovak: 'východ', category: 'directions' },
    { english: 'west', slovak: 'západ', category: 'directions' },
    { english: 'up', slovak: 'hore', category: 'directions' },
    { english: 'down', slovak: 'dole', category: 'directions' },
    { english: 'left', slovak: 'vľavo', category: 'directions' },
    { english: 'right', slovak: 'vpravo', category: 'directions' },
  ],
  time: [
    { english: 'hour', slovak: 'hodina', category: 'time' },
    { english: 'minute', slovak: 'minúta', category: 'time' },
    { english: 'second', slovak: 'sekunda', category: 'time' },
    { english: 'morning', slovak: 'ráno', category: 'time' },
    { english: 'noon', slovak: 'poludnie', category: 'time' },
    { english: 'afternoon', slovak: 'popoludnie', category: 'time' },
    { english: 'evening', slovak: 'večer', category: 'time' },
    { english: 'night', slovak: 'noc', category: 'time' },
    { english: 'week', slovak: 'týždeň', category: 'time' },
    { english: 'month', slovak: 'mesiac', category: 'time' },
    { english: 'year', slovak: 'rok', category: 'time' },
    { english: 'today', slovak: 'dnes', category: 'time' },
    { english: 'tomorrow', slovak: 'zajtra', category: 'time' },
    { english: 'yesterday', slovak: 'včera', category: 'time' },
  ],
  commonPhrases: [
    { english: 'What\'s your name?', slovak: 'Ako sa voláš?', category: 'common phrases' },
    { english: 'My name is...', slovak: 'Volám sa...', category: 'common phrases' },
    { english: 'How are you?', slovak: 'Ako sa máš?', category: 'common phrases' },
    { english: 'I\'m fine, thank you.', slovak: 'Mám sa dobre, ďakujem.', category: 'common phrases' },
    { english: 'Where are you from?', slovak: 'Odkiaľ si?', category: 'common phrases' },
    { english: 'I\'m from...', slovak: 'Som z...', category: 'common phrases' },
    { english: 'Do you speak English?', slovak: 'Hovoríš po anglicky?', category: 'common phrases' },
    { english: 'Yes, a little.', slovak: 'Áno, trochu.', category: 'common phrases' },
    { english: 'No, I don\'t speak Slovak.', slovak: 'Nie, nehovorím po slovensky.', category: 'common phrases' },
    { english: 'Where is the bathroom?', slovak: 'Kde je toaleta?', category: 'common phrases' },
    { english: 'How much does it cost?', slovak: 'Koľko to stojí?', category: 'common phrases' },
    { english: 'Can you help me, please?', slovak: 'Môžete mi pomôcť, prosím?', category: 'common phrases' },
  ],
  food: [
    { english: 'bread', slovak: 'chlieb', category: 'food' },
    { english: 'water', slovak: 'voda', category: 'food' },
    { english: 'milk', slovak: 'mlieko', category: 'food' },
    { english: 'coffee', slovak: 'káva', category: 'food' },
    { english: 'tea', slovak: 'čaj', category: 'food' },
    { english: 'soup', slovak: 'polievka', category: 'food' },
    { english: 'salad', slovak: 'šalát', category: 'food' },
    { english: 'meat', slovak: 'mäso', category: 'food' },
    { english: 'chicken', slovak: 'kurča', category: 'food' },
    { english: 'beef', slovak: 'hovädzie', category: 'food' },
    { english: 'pork', slovak: 'bravčové', category: 'food' },
    { english: 'fish', slovak: 'ryba', category: 'food' },
    { english: 'vegetables', slovak: 'zelenina', category: 'food' },
    { english: 'fruit', slovak: 'ovocie', category: 'food' },
    { english: 'egg', slovak: 'vajce', category: 'food' },
    { english: 'cheese', slovak: 'syr', category: 'food' },
    { english: 'butter', slovak: 'maslo', category: 'food' },
    { english: 'oil', slovak: 'olej', category: 'food' },
    { english: 'salt', slovak: 'soľ', category: 'food' },
    { english: 'sugar', slovak: 'cukor', category: 'food' },
  ],
  animals: [
    { english: 'dog', slovak: 'pes', category: 'animals' },
    { english: 'cat', slovak: 'mačka', category: 'animals' },
    { english: 'horse', slovak: 'kôň', category: 'animals' },
    { english: 'cow', slovak: 'krava', category: 'animals' },
    { english: 'pig', slovak: 'prasa', category: 'animals' },
    { english: 'chicken', slovak: 'kurča', category: 'animals' },
    { english: 'sheep', slovak: 'ovca', category: 'animals' },
    { english: 'goat', slovak: 'koza', category: 'animals' },
    { english: 'duck', slovak: 'kačica', category: 'animals' },
    { english: 'goose', slovak: 'hus', category: 'animals' },
    { english: 'rabbit', slovak: 'králik', category: 'animals' },
    { english: 'mouse', slovak: 'myš', category: 'animals' },
    { english: 'rat', slovak: 'krysa', category: 'animals' },
    { english: 'snake', slovak: 'had', category: 'animals' },
    { english: 'bird', slovak: 'vták', category: 'animals' },
    { english: 'fish', slovak: 'ryba', category: 'animals' },
    { english: 'frog', slovak: 'žaba', category: 'animals' },
    { english: 'turtle', slovak: 'korytnačka', category: 'animals' },
    { english: 'elephant', slovak: 'slon', category: 'animals' },
    { english: 'lion', slovak: 'lev', category: 'animals' },
    { english: 'tiger', slovak: 'tiger', category: 'animals' },
    { english: 'bear', slovak: 'medveď', category: 'animals' },
    { english: 'wolf', slovak: 'vlk', category: 'animals' },
    { english: 'fox', slovak: 'liška', category: 'animals' },
    { english: 'monkey', slovak: 'opica', category: 'animals' },
    { english: 'kangaroo', slovak: 'kangarú', category: 'animals' },
    { english: 'penguin', slovak: 'tučniak', category: 'animals' },
    { english: 'crocodile', slovak: 'krokodíl', category: 'animals' },
    { english: 'hippopotamus', slovak: 'hipopótam', category: 'animals' },
    { english: 'rhinoceros', slovak: 'nosorožec', category: 'animals' },
    { english: 'giraffe', slovak: 'žirafa', category: 'animals' },
    { english: 'zebra', slovak: 'zebra', category: 'animals' },
    { english: 'camel', slovak: 'dromedár', category: 'animals' },
    { english: 'deer', slovak: 'jelen', category: 'animals' },
    { english: 'moose', slovak: 'los', category: 'animals' },
    { english: 'buffalo', slovak: 'bufalo', category: 'animals' },
    { english: 'gorilla', slovak: 'gorila', category: 'animals' },
    { english: 'parrot', slovak: 'papagáj', category: 'animals' },
    { english: 'owl', slovak: 'sova', category: 'animals' },
    { english: 'eagle', slovak: 'orol', category: 'animals' },
    { english: 'hawk', slovak: 'jestreb', category: 'animals' },
    { english: 'vulture', slovak: 'sup', category: 'animals' },
    { english: 'flamingo', slovak: 'plameniak', category: 'animals' },
    { english: 'stork', slovak: 'bocian', category: 'animals' },
    { english: 'swan', slovak: 'labuť', category: 'animals' },
    { english: 'crane', slovak: 'žeriav', category: 'animals' },
    { english: 'heron', slovak: 'čáp', category: 'animals' },
    { english: 'seagull', slovak: 'morská lastovička', category: 'animals' },
    { english: 'pelican', slovak: 'pelikán', category: 'animals' },
    { english: 'albatross', slovak: 'albatros', category: 'animals' },
    { english: 'dolphin', slovak: 'delfín', category: 'animals' },
    { english: 'whale', slovak: 'veľryba', category: 'animals' },
    { english: 'shark', slovak: 'žralok', category: 'animals' },
    { english: 'seal', slovak: 'tuleň', category: 'animals' },
    { english: 'walrus', slovak: 'mrož', category: 'animals' },
    { english: 'octopus', slovak: 'chobotnica', category: 'animals' },
    { english: 'jellyfish', slovak: 'medúza', category: 'animals' },
    { english: 'starfish', slovak: 'morská hviezda', category: 'animals' },
    { english: 'shell', slovak: 'lastúra', category: 'animals' },
    { english: 'coral', slovak: 'koral', category: 'animals' },
    { english: 'clam', slovak: 'mušľa', category: 'animals' },
    { english: 'oyster', slovak: 'ustrica', category: 'animals' },
  ],
  body: [
    { english: 'head', slovak: 'hlava', category: 'body' },
    { english: 'hair', slovak: 'vlasy', category: 'body' },
    { english: 'face', slovak: 'tvár', category: 'body' },
    { english: 'eye', slovak: 'oko', category: 'body' },
    { english: 'ear', slovak: 'ucho', category: 'body' },
    { english: 'nose', slovak: 'nos', category: 'body' },
    { english: 'mouth', slovak: 'ústa', category: 'body' },
    { english: 'lip', slovak: 'pery', category: 'body' },
    { english: 'tooth', slovak: 'zub', category: 'body' },
    { english: 'tongue', slovak: 'jazyk', category: 'body' },
    { english: 'neck', slovak: 'krk', category: 'body' },
    { english: 'shoulder', slovak: 'rameno', category: 'body' },
    { english: 'arm', slovak: 'ruka', category: 'body' },
    { english: 'elbow', slovak: 'lakť', category: 'body' },
    { english: 'wrist', slovak: 'zapestie', category: 'body' },
    { english: 'hand', slovak: 'ruka', category: 'body' },
    { english: 'finger', slovak: 'prst', category: 'body' },
    { english: 'thumb', slovak: 'palce', category: 'body' },
    { english: 'back', slovak: 'chrbát', category: 'body' },
    { english: 'chest', slovak: 'hrudník', category: 'body' },
    { english: 'stomach', slovak: 'žalúdok', category: 'body' },
    { english: 'waist', slovak: 'pas', category: 'body' },
    { english: 'hip', slovak: 'bok', category: 'body' },
    { english: 'leg', slovak: 'noha', category: 'body' },
    { english: 'thigh', slovak: 'stehno', category: 'body' },
    { english: 'knee', slovak: 'koleno', category: 'body' },
    { english: 'ankle', slovak: 'kotník', category: 'body' },
    { english: 'foot', slovak: 'noha', category: 'body' },
    { english: 'toe', slovak: 'prst na nohe', category: 'body' },
    { english: 'skin', slovak: 'koža', category: 'body' },
    { english: 'blood', slovak: 'krv', category: 'body' },
    { english: 'bone', slovak: 'kosť', category: 'body' },
    { english: 'muscle', slovak: 'sval', category: 'body' },
    { english: 'heart', slovak: 'srdce', category: 'body' },
    { english: 'lung', slovak: 'pľúca', category: 'body' },
    { english: 'liver', slovak: 'pečeň', category: 'body' },
    { english: 'kidney', slovak: 'oblička', category: 'body' },
    { english: 'stomach', slovak: 'žalúdok', category: 'body' },
    { english: 'intestines', slovak: 'črevá', category: 'body' },
    { english: 'bladder', slovak: 'močový mechúr', category: 'body' },
    { english: 'brain', slovak: 'mozog', category: 'body' },
    { english: 'nerve', slovak: 'nerov', category: 'body' },
    { english: 'spine', slovak: 'chrbtica', category: 'body' },
    { english: 'skull', slovak: 'lebka', category: 'body' },
    { english: 'rib', slovak: 'rebrá', category: 'body' },
    { english: 'joint', slovak: 'kĺb', category: 'body' },
    { english: 'vein', slovak: 'žila', category: 'body' },
    { english: 'artery', slovak: 'artéria', category: 'body' },
  ],
  clothes: [
    { english: 'shirt', slovak: 'košeľa', category: 'clothes' },
    { english: 'blouse', slovak: 'blúzka', category: 'clothes' },
    { english: 't-shirt', slovak: 'tričko', category: 'clothes' },
    { english: 'sweater', slovak: 'sveter', category: 'clothes' },
    { english: 'jacket', slovak: 'bunda', category: 'clothes' },
    { english: 'coat', slovak: 'plášť', category: 'clothes' },
    { english: 'pants', slovak: 'nohavice', category: 'clothes' },
    { english: 'jeans', slovak: 'džínsy', category: 'clothes' },
    { english: 'skirt', slovak: 'sukňa', category: 'clothes' },
    { english: 'dress', slovak: 'šaty', category: 'clothes' },
    { english: 'shorts', slovak: 'krátke nohavice', category: 'clothes' },
    { english: 'socks', slovak: 'ponožky', category: 'clothes' },
    { english: 'shoes', slovak: 'topánky', category: 'clothes' },
    { english: 'sneakers', slovak: 'tenisky', category: 'clothes' },
    { english: 'boots', slovak: 'čižmy', category: 'clothes' },
    { english: 'sandals', slovak: 'sandále', category: 'clothes' },
    { english: 'hat', slovak: 'čiapka', category: 'clothes' },
    { english: 'cap', slovak: 'čiapka s dasťovou zásterou', category: 'clothes' },
    { english: 'gloves', slovak: 'rukavice', category: 'clothes' },
    { english: 'scarf', slovak: 'šál', category: 'clothes' },
    { english: 'tie', slovak: 'kravata', category: 'clothes' },
    { english: 'belt', slovak: 'opasok', category: 'clothes' },
    { english: 'button', slovak: 'gombík', category: 'clothes' },
    { english: 'zipper', slovak: 'zips', category: 'clothes' },
    { english: 'pocket', slovak: 'vrecko', category: 'clothes' },
    { english: 'collar', slovak: 'galoša', category: 'clothes' },
    { english: 'sleeve', slovak: 'rukáv', category: 'clothes' },
    { english: 'hem', slovak: 'lem', category: 'clothes' },
    { english: 'lace', slovak: 'šnúrka', category: 'clothes' },
    { english: 'lining', slovak: 'podšípanie', category: 'clothes' },
  ],
};

// Function to populate vocabulary
async function populateVocab() {
  try {
    // Clear existing data
    await Vocabulary.deleteMany({});
    
    // Loop through categories and insert data
    for (const category in categories) {
      if (Object.hasOwnProperty.call(categories, category)) {
        const vocabData = categories[category];
        await Vocabulary.insertMany(vocabData);
      }
    }
    
    console.log('Vocabulary populated successfully.');
  } catch (error) {
    console.error('Error populating vocabulary:', error);
  } finally {
    // Disconnect from MongoDB
    mongoose.disconnect();
  }
}

// Populate the vocabulary
populateVocab();
